Med_store/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from Billing.views import guest_register_page,payment_method_view
urlpatterns = [
    url('admin/', admin.site.urls),
    url('register/guest', guest_register_page, name='guest_register'),
# url('payment_method', payment_method_view, name='payment_method_view'),
url('accounts/', include(("accounts.urls",'accounts'),namespace='accounts')),
url('products/', include(("products.urls",'products'),namespace='products')),
url('carts/', include(("carts.urls",'carts'),namespace='carts')),
url('', include(("Billing.urls",'Billing'),namespace='Billing')),
url('admin_panel/', include(("administration.urls",'administration'),namespace='administration')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from.views import login_page,register_page
#guest_register_page
urlpatterns = [
    url('login', login_page,name='login'),
url('logout/', LogoutView.as_view(), name='logout'),
    url('register', register_page, name='register'),
    # url('register/guest', guest_register_page, name='guest_register'),

]

carts/urls.py
from django.contrib import admin
from django.conf.urls import url
from.views import cart_home,cart_update,checkout_home,checkout_done_view

urlpatterns = [
    url(r'^$', cart_home,name='cart_view'),
 url(r'^checkout',checkout_home,name='checkout'),
url('(?P<slug>[\w-]+)/$',cart_update,name='update'),
url(r'^success',checkout_done_view,name='success'),
# url('update/(?P<qty>\d+)/$',cart_update,name='update'),

]

products/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from.views import ProductListView,ProductDetailView,home

urlpatterns = [
    url('admin_panel/', admin.site.urls),
    url(r'^home$',home, name='home'),
    url(r'^$', ProductListView.as_view(), name='list'),
    url('(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail')
]

templates/base/css.html
     {% load staticfiles %}

      <link rel='stylesheet' type='text/css' href='{% static "budjet.css" %}'>
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<!--     fontawesome-->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">




  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <![endif]-->

<!--  <script>-->
<!--$(document).ready(function(){-->
<!--    $("p").click(function(){-->
<!--        $(this).hide();-->
<!--    });-->
<!--});-->
<!--</script>-
<style>
    @import url('https://fonts.googleapis.com/css?family=Monda&display=swap');
    .navbar-brand {
    float: left;
    height: 50px;
    padding: 15px 15px;
    font-size: 28px;
    font-family: 'Monda', sans-serif;
    line-height: 20px;
}
.nav li a {
    color: red;
}
.navbar-inverse {
    background-color: #222;
    border-color: #080808;
    padding:10px;
}
</style>

templates/base/footer.html
<div >
 	<div class="alert alert-secondary footer" role="alert" style="min-height: 200px;margin-bottom:5px;background-color: #999">
	       footer
	</div>
</div>

templates/base/js.html
 {% load staticfiles %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
   
   <!--  jquery confirm -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

templates/base/navbar.html
{% url 'products:home' as home_url  %}
{% url 'products:list' as list_url %}
{% url 'contact' as contact_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% url 'carts:cart_view' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <div class="container">
  <a class="navbar-brand" style="font-size: 25px;" href="{{home_url}}">ePharma</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {%if request.path == home_url%}active{%endif%}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {%if request.path == list_url%}active{%endif%}">
        <a class="nav-link" href="{{list_url}}">Product</a>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>


      {%if request.user.is_authenticated%}
      <li class="nav-item {%if request.path == contact_url%}active{%endif%}">
        <a class="nav-link " href="{{contact_url}}" tabindex="-1" aria-disabled="true">Contact</a>
      </li>
      </li>
      <li class="nav-item ">
        <a class="nav-link " href="{{logout_url}}" tabindex="-1" aria-disabled="true">Logout</a>
      </li>
      {% else%}
         <li class="nav-item {%if request.path == login_url%}active{%endif%}">
        <a class="nav-link " href="{{login_url}}" tabindex="-1" aria-disabled="true">Login</a>
      </li>
      <li class="nav-item {%if request.path == register_url%}active{%endif%}">
        <a class="nav-link " href="{{register_url}}" tabindex="-1" aria-disabled="true">register</a>
      </li>
      {%endif%}
        </li>
         <li class="nav-item {%if request.path == cart_url%}active{%endif%}">
        <a class="nav-link " href="{{cart_url}}"><span class="glyphicon glyphicon-shopping-cart"></span> <span class="navbar-cart-count"> {{request.session.cart_items}}</span></a>
      </li>

    </ul>
  </div>
  </div>
</nav>

templates/base/new_nav.html
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
     <title>{% block title %} My Site {% endblock %}</title>

     {% load staticfiles %}

      
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <![endif]-->

<!--  <script>-->
<!--$(document).ready(function(){-->
<!--    $("p").click(function(){-->
<!--        $(this).hide();-->
<!--    });-->
<!--});-->
<!--</script>-->
  </head>


    <style>
  body {
      position: relative; 
  }
  </style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">  
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="#section1">Section 1</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#section2">Section 2</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#section3">Section 3</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Section 4
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#section41">Link 1</a>
        <a class="dropdown-item" href="#section42">Link 2</a>
      </div>
    </li>
  </ul>
</nav>

dfgh
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Bootstrap Tutorial</h1>      
    <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.</p>
  </div>
</div>


<div id="section1" class="container-fluid bg-success" style="padding-top:70px;padding-bottom:70px">
  <h1>Section 1</h1>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
</div>
<div id="section2" class="container-fluid bg-warning" style="padding-top:70px;padding-bottom:70px">
  <h1>Section 2</h1>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
</div>
<div id="section3" class="container-fluid bg-secondary" style="padding-top:70px;padding-bottom:70px">
  <h1>Section 3</h1>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
</div>
<div id="section41" class="container-fluid bg-danger" style="padding-top:70px;padding-bottom:70px">
  <h1>Section 4 Submenu 1</h1>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
</div>
<div id="section42" class="container-fluid bg-info" style="padding-top:70px;padding-bottom:70px">
  <h1>Section 4 Submenu 2</h1>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
  <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
</div>

</body>
</html>