Med_store/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from Billing.views import guest_register_page,payment_method_view
urlpatterns = [
    url('admin/', admin.site.urls),
    url('register/guest', guest_register_page, name='guest_register'),
# url('payment_method', payment_method_view, name='payment_method_view'),
url('accounts/', include(("accounts.urls",'accounts'),namespace='accounts')),
url('products/', include(("products.urls",'products'),namespace='products')),
url('carts/', include(("carts.urls",'carts'),namespace='carts')),
url('', include(("Billing.urls",'Billing'),namespace='Billing')),
url('admin_panel/', include(("administration.urls",'administration'),namespace='administration')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


administration/urls.py
from django.contrib import admin
from django.conf.urls import url
from.views import home,add_product,ProductListView,update,delete
urlpatterns = [
    url(r'home', home,name='home'),
      # url(r'index', index,name='home'),
    url(r'list',ProductListView.as_view(), name='list'),
    url(r'add', add_product, name='add'),
url(r'update/(?P<slug>[\w-]+)/$', update, name='update'),
url(r'delete/(?P<slug>[\w-]+)/$', delete, name='delete'),

]

carts/urls.py
from django.contrib import admin
from django.conf.urls import url
from.views import cart_home,cart_update,checkout_home,checkout_done_view

urlpatterns = [
    url(r'^$', cart_home,name='cart_view'),
 url(r'^checkout',checkout_home,name='checkout'),
url('(?P<slug>[\w-]+)/$',cart_update,name='update'),
url(r'^success',checkout_done_view,name='success'),
# url('update/(?P<qty>\d+)/$',cart_update,name='update'),

]

administration/models.py
from django.db import models

# Create your models here.

administration/forms.py
from django import forms
from products.models import Product,Category
class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['title','description','price','category','image']
class ProductCategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=['title',]

administration/views.py
from django.shortcuts import render,redirect
from.forms import ProductForm
from django.views.generic import ListView,DetailView
from products.models import Product
# Create your views here.
def home(request):
    return render(request,'administration/home.html')
def view_order(request):
    return render(request,'administration/home.html')

class ProductListView(ListView):
    template_name ='administration/list_product.html'
    def get_queryset(self):
        self.request
        return Product.objects.all
def add_product(request):
    form=ProductForm(request.POST , request.FILES)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            return redirect('administration:list')
    else:
        form=ProductForm()
    context={
        "form":form,
    }
    return render(request,'administration/add_product.html',context)

def update(request,slug):
    product_form=Product.objects.get(slug=slug)
    form=ProductForm(instance=product_form)
    if request.method=='POST':
        form = ProductForm(request.POST, request.FILES,instance=product_form)
        if form.is_valid():
            form.save()

            return redirect('administration:list')
    context={
        "form":form,
    }
    return render(request,'administration/add_product.html',context)
def delete(request,slug):
    product_form = Product.objects.get(slug=slug)
    if request.method=="POST":
        product_form.delete()
        return redirect('administration:list')
    context={
        "product":product_form
    }
    return render(request,'administration/delete.html',context)


administration/templates/administration/add_product.html
{% extends 'admin_base.html'%}
{%block content%}
{% load crispy_forms_tags %}

<!-- <div class="main-content">
    <div class="row">
        <div class="col-6">
             <form action=""method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form|crispy}}
                <button class="btn btn-success my-3" type="submit">Add</button>
            </form>
        </div>
    </div>

</div> -->
<style type="text/css">
	.card{
		width:50%;
		left:400px;
	}
	@media screen and (min-width: 600px) {
		.container{
			background-color: red;
			
			left: 100px;

		}
		.card{
		width:60%;
		left:150px;
	}
	}
	@media screen and (min-width: 800px) {
		.card{
		width:50%;
		left:400px;
	}
	}
	@media screen and (min-width: 300px) {
		.card{
		width:90%;
		left:20px;
		
	}

	}
</style>

	<div class="main-content">
			<div class="title">
				Add Product
			</div>
			
			<div class="main">
				<div class="widget1">
			 <div class="row">
        <div class="col-md-6 col-6-lg col-6-sm">
        	<h4>Product category</h4>
        	<hr>
             <form action=""method="post" enctype="multipart/form-data"style="left: 500px;">
                {%csrf_token%}
                {{form|crispy}}
                <button class="btn btn-success my-3" type="submit">Add</button>
            </form>
        </div>
        </div>
				
			</div>
		</div>

{%endblock %}

administration/templates/administration/admin_base_head.html
{% url 'administration:add' as add_url %}

<style>
			.ad {
				position: absolute;
				width: 300px;
				height: 250px;
				border: 1px solid #ddd;
				left: 50%;
				transform: translateX(-50%);
				top: 250px;
				z-index: 10;
			}
			.ad .close {
				position: absolute;
				font-family: 'ionicons';
				width: 20px;
				height: 20px;
				color: #fff;
				background-color: #999;
				font-size: 20px;
				left: -20px;
				top: -1px;
				display: table-cell;
				vertical-align: middle;
				cursor: pointer;
				text-align: center;
			}
		</style>
		<script type="text/javascript">
			
			$(document).ready(function() {
	$('.nav-trigger').click(function() {
		$('.side-nav').toggleClass('visible');
	});
});
		</script>
		<script type="text/javascript">

			$(function() {
				$('.close').click(function() {
					$('.ad').css('display', 'none');
				})
			})



		</script>

	</head>

	<body style="background-color: #d5dae5;">
		<div class="header">
			<div class="logo">
				<i class="fa fa-tachometer"></i>
				<span>Brand</span>
			</div>
			<a href="#" class="nav-trigger"><span></span></a>
		</div>
		<div class="side-nav">
			<div class="logo">
				<i class="fa fa-tachometer"></i>
				<span>Brand</span>
			</div>
			<nav>
				<ul>
					<li>
						<a href="#">
							<span><i class="fa fa-user"></i></span>
							<span>Users</span> 
						</a>
					</li>
					<li data-toggle="modal" data-target="#myModal">
						<a href="{{add_url}}" >

							<span><i class="fa fa-envelope"></i></span>
							<span>Add Product</span>
						</a>
					</li>

					<li>
						<a href="{%url 'administration:list'%}">

							<span><i class="fa fa-envelope"></i></span>
							<span>view product</span>
						</a>
					</li>
					<li>
						<a href="#">

							<span><i class="fa fa-envelope"></i></span>
							<span>view Orders</span>
						</a>
					</li>



					<li class="active">
						<a href="#">
							<span><i class="fa fa-bar-chart"></i></span>
							<span>Analytics</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span><i class="fa fa-credit-card-alt"></i></span>
							<span>Payments</span>
						</a>
					</li>
				</ul>
			</nav>
		</div>



administration/templates/administration/delete.html
{% extends 'admin_base.html'%}
{%block content%}
<div class="container">
<h3>Are you sure you want to delete {{product}}</h3>
<form action=""method="post">
    {%csrf_token%}
    <a href="{%url 'administration:list'%}">Cancel</a>
    <input class="btn btn-primary" type="submit" name="confirm">
</form>
</div>
{%endblock%}

administration/templates/administration/home.html
{% extends 'admin_base.html'%}

{% block content%}

		<div class="main-content">
			<div class="title">
				Analytics
			</div>
			
			<div class="main">
				<div class="widget1">
					<div class="title">Number of views</div>
					<div class="chart"></div>
				</div>
				<div class="widget2">
					<div class="title">Number of likes</div>
					<div class="chart"></div>
				</div>
				<div class="widget3">
					<div class="title">Number of comments</div>
					<div class="chart"></div>
				</div>
			</div>
		</div>
		
{%endblock%}

administration/templates/administration/index.html
{% extends 'admin_base.html'%}

{% block content%}
<script type="text/javascript">
function toggleSideBar() {
	document.getElementById('side-nav').classList.toggle('active')
}
</script>
<!-- <div class="header">
    <div class="logo">
        <i class="fa fa-tachometer"></i>
        <span>Brand</span>
    </div>
    <a href="#" class="nav-trigger"><span></span></a>
</div> -->

<div class="side-nav" id="side-nav">
	   <div class="logo">
        <i class="fa fa-tachometer"></i>
        <span>Brand</span>
    </div>
    <div class="toggle-btn" onclick="toggleSideBar()">
    	<span></span>
    	<span></span>
    	<span></span>
    </div>
	<nav>
		<ul>
			<li>
				<a href="">
					<span><i class="fa fa-user"></i></span>
					<span>User</span>
				</a>
			</li>
			<li>
				<a href="">
					<span><i class="fa fa-envelope"></i></span>
					<span>Message</span>
				</a>
			</li>
			<li class="active">
				<a href="">
					<span><i class="fa fa-user"></i></span>
					<span>Analyticts</span>
				</a>
			</li>
		</ul>
	</nav>
</div>

<div class="main-content">
	<div class="container">
<div class="card-deck">
  <div class="card bg-primary">
    <div class="card-body text-center">
      <p class="card-text">Some text inside the first card</p>
    </div>
  </div>
  <div class="card bg-warning">
    <div class="card-body text-center">
      <p class="card-text">Some text inside the second card</p>
    </div>
  </div>
  <div class="card bg-success">
    <div class="card-body text-center">
      <p class="card-text">Some text inside the third card</p>
    </div>
  </div>
  <div class="card bg-danger">
    <div class="card-body text-center">
      <p class="card-text">Some text inside the fourth card</p>
    </div>
  </div>
</div>
</div>
</div>
{%endblock%}

administration/templates/administration/index2.html
{% extends 'admin_base.html'%}

{% block content%}
<script type="text/javascript">
	
	function openSlideMenu() {
	document.getElementById('menu').style.width='250px';
	document.getElementById('content').style.marginLeft='250px';
}

function closeSlideMenu() {
	document.getElementById('menu').style.width='0';
	document.getElementById('content').style.marginLeft='0';
}
</script>
<div id="content">
	<span class="slide">
		<a href="" onclick="openSlideMenu()">
			<i class="fas fa-bars"></i>
		</a>
	</span>

	<div id="menu" class="nav">
		<a href="" onclick=" closeSlideMenu()">
			<i class="fas fa-times"></i>
		</a>

	  	<a href="">Home</a>
	  	<a href="">about</a>
	  	<a href="">Contact</a>
	</div>
	<h1>RESPONSIVE HOHWHIOBOWEBF0IF'FEOFH</h1>
</div>

{%endblock%}

administration/templates/administration/list_product.html
{% extends 'admin_base.html'%}
{%block content%}
<div class="container">
<table class="table">
    <thead class="thead-dark">
    <th>No</th>
    <th>Product Name</th>
    <th>Product Description</th>
    <th>Price</th>
    <th>category</th>
    <th colspan="2">Action</th>
    </thead>
    <tbody>

    <tr>
        {%for obj in object_list%}
        <td>{{forloop.counter}}</td>
        <td>{{obj.title}}</td>
        <td>{{obj.description}}</td>
        <td>{{obj.price}}</td>
        {%for cat in obj.category.all%}
        <td>{{cat}}</td>
        <td><a href="{% url 'administration:update' obj.slug %}" type="button">Update</a></td>
         <td><a href="{% url 'administration:delete' obj.slug %}" type="button">Delete</a></td>
        {%endfor%}

    </tr>
    {%endfor%}
    </tbody>
</table>
</div>

{%endblock%}