Med_store/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from Billing.views import guest_register_page,payment_method_view
urlpatterns = [
    url('admin/', admin.site.urls),
    url('register/guest', guest_register_page, name='guest_register'),
# url('payment_method', payment_method_view, name='payment_method_view'),
url('accounts/', include(("accounts.urls",'accounts'),namespace='accounts')),
url('products/', include(("products.urls",'products'),namespace='products')),
url('carts/', include(("carts.urls",'carts'),namespace='carts')),
url('', include(("Billing.urls",'Billing'),namespace='Billing')),
url('admin_panel/', include(("administration.urls",'administration'),namespace='administration')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


carts/urls.py
from django.contrib import admin
from django.conf.urls import url
from.views import cart_home,cart_update,checkout_home,checkout_done_view

urlpatterns = [
    url(r'^$', cart_home,name='cart_view'),
 url(r'^checkout',checkout_home,name='checkout'),
url('(?P<slug>[\w-]+)/$',cart_update,name='update'),
url(r'^success',checkout_done_view,name='success'),
# url('update/(?P<qty>\d+)/$',cart_update,name='update'),

]

carts/models.py
from django.db import models
from products.models import Product
from django.conf import settings
from django.db.models.signals import pre_save,m2m_changed

User=settings.AUTH_USER_MODEL
# Create your models here.
class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id = request.session.get('cart_id', None)
        qs =self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
           new_obj = False
           cart_obj = qs.first()
           if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj =Cart.objects.new(user=request.user)
            new_obj=True
            request.session['cart_id'] = cart_obj.id
        return cart_obj,new_obj
    #create the cart
    def new(self,user=None):
        print(user)
        user_obj=None
        if user is not None:
            if user.is_authenticated:
                user_obj=user
        return self.model.objects.create(user=user_obj)

class CartItem(models.Model):
    cart = models.ForeignKey('Cart',on_delete='CASCADE', null=True, blank=True)
    products = models.ForeignKey(Product,on_delete='CASCADE', blank=True,null=True)
    quantity=models.PositiveIntegerField(default=1)
    linetotal = models.DecimalField(default=10.99, max_digits=100, decimal_places=2)
    objects = CartManager()

    def __str__(self):
        try:
            return str(self.products)
        except:
            return self.products.title
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete='CASCADE',null=True,blank=True)
    # items=models.ManyToManyField(CartItem,null=True,blank=True)
    # product=models.ManyToManyField(CartItem,blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    objects=CartManager()
    def __str__(self):
        return "Cart id:%s"% (self.id)

# def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
#     print(action)
#     if action == 'post_add' or action=='post_remove' or action=='post_clear':
#
#          # print(instance.total)
#         print(instance.product.all())
#
#         prod = instance.product.all()
#         total = 0
#         for x in prod:
#              line_total = float(x.products.price) * x.quantity
#              total += line_total
#         print('x',total)
#         if instance.subtotal!=total:
#             instance.subtotal=total
#             instance.save()
# m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.product.through)

# def pre_save_cart_receiver(sender,instance,*args,**kwargs):
# # #     if instance.subtotal>0:
# # #         instance.total=instance.subtotal + 10
# # #     else:
# # #         instance.total =0.00
# # #
# # # pre_save.connect(pre_save_cart_receiver,sender=Cart)

carts/views.py
from django.shortcuts import render,redirect
from.models import Product,Cart,CartItem
from Orders.models import Order
from accounts.forms import LoginForm,GuestForm
from Billing.models import BillingProfile
from accounts.models import GuestEmail

# Create your views here.
def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products=cart_obj.cartitem_set.all()
    total=0
    for x in products:
        line_total = float(x.products.price) * x.quantity
        total += line_total
    print(total)
    print(cart_obj.total)
    cart_obj.total=total
    cart_obj.save()

    return render(request,'cart_home.html',{'cart':cart_obj})
def cart_update(request,slug):
    try:
        qty=request.GET.get('qty')
        update_qty = True
    except:
        qty=None
        update_qty=False
    try:
        product_obj=Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        print('product out of stock')
        return redirect('carts:cart_view')
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    cart_item, created = CartItem.objects.get_or_create(cart=cart_obj,products=product_obj )
    if created:
            print('created')
    if  update_qty and qty :
        if int(qty)==0 :
            cart_item.delete()
        else:
            cart_item.quantity=qty
            cart_item.save()
    else:
        pass
        # if product_obj in cart_obj.items.all():
        #     cart_obj.items.remove(cart_item)
        # else:
        #     cart_obj.items.add(cart_item)
    products = cart_obj.cartitem_set.all()
    request.session['cart_items'] = cart_obj.cartitem_set.count()


    return redirect('carts:cart_view')

def checkout_home(request):
    cart_obj,cart_created=Cart.objects.new_or_get(request)
    order_obj=None
    if  cart_created or cart_obj.cartitem_set.count()==0:
        redirect('carts:cart_view')
    login_form=LoginForm()
    guest_form=GuestForm()
    # billing model manager
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    if billing_profile is not None:
        # order model manager
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        # finalize checkout
    if request.method == "POST":
        "check the order is done"
        is_done = order_obj.check_done()

        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']


        return redirect('carts:success')
    context={
        'billing_profile':billing_profile,
        'object': order_obj,
        'login_form':login_form,
        'guest_form':guest_form
    }
    return render(request,'checkout.html',context)

def checkout_done_view(request):
    return render(request,"checkout_done.html")

carts/templates/cart_home.html
{%extends 'base.html'%}
{%block content%}
<div class="container">

  <div class="row">
      <!-- first collumn show items -->
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="alert " role="alert" style="min-height: 200px;margin-top:50px;background-color: #fff;">
                    <p><h3>Shopping Cart</h3></p>
                    <hr>
          <div class="col" >
            {%if cart.cartitem_set.exists%}
             <table class="table table-borderless" >
 
    <tbody>
      <tr>
          {%for prod in cart.cartitem_set.all%}
          <td><img src="{{prod.products.image.url}}" style="width: 100px;"></td>
        <td>{{prod.products}} <br>
         <p> <h6 style="color: green;">${{prod.products.price}} </h6><hr> 
         </p>

        </td>

        <td>{{prod.quantity}}</td>
        <td >
          <span class="glyphicon glyphicon-shopping-cart"></span>
          <a href="{%url 'carts:update' prod.products.slug%}?qty=0">remove</a></td>

        <td class="glyphicon glyphicon-shopping-cart"></td>
      </tr>
        {%endfor%}

    </tbody>
  </table>

  {% else %}
<p class="lead"> <h5>Cart is empty </h5></p>

{%endif%}
 <a href=" " class="btn " style="background-color: #16a085;color: 
     #fff;">Continue shopping<a/>
          </div>
        </div>
    </div>

      <!-- first row show items and total price  -->
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div div class="alert " role="alert" style="min-height: 200px;margin-top:50px;background-color: #fff;">
           <div class="row">
                  <div class="col-sm-1 col-md-1 col-lg">
                    <p>{{request.session.cart_items}} Items</p>
                    <br>  
                    <p> Tax</p>
                  </div>
                  <div class="col">
                 <p style="color: green;" class="text-right"><span class="cart-subtotal"> <b> ${{cart.total}}</b></span></p>
                 <br>   

                  <p style="color: green;" class="text-right"><span class="cart-subtotal"> <b> $0.00</b></span></p>                 
               </div>

            </div>
          <hr>

            <div class="row">
                  <div class="col-sm-1 col-md-1 col-lg">
                    <p>Total</p>
                  </div>
                  <div class="col">
                 <p style="color: green;" class="text-right"><span class="cart-subtotal"> <b> ${{cart.total}}</b></span></p>                   
               </div>

            </div>
                  <hr>      
                <div class="row">
                  <div class="col-sm-2 col-md-2 col-lg-2">
                 <a  href="{%url 'carts:checkout'%}">
                  <button class="btn  btn-dark" style="margin-left: 95px;" >Checkout</button>
                 </a>

               </div>

            </div>
              


      </div>

    </div>
  </div>

   
</div>
{%endblock%}

carts/templates/checkout.html
{%extends 'base.html'%}
{%block content%}
{{object.order_id}}--{{object.cart}}
{%if not billing_profile%}
<div class="row text-center" >
<div class="col-12 col-md-6">
    login
    {% include 'snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
</div>
<div class="col-12 col-md-6">
  contine as guest
             {% url 'guest_register' as guest_register_url%}
      {%include 'snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
</div>
</div>
{%else%}
           <h1>Finalize Checkout</h1>
            <p>Cart Total: {{object.cart.total}}</p>
            <p>Order Total: {{object.total}}</p>
        <form action="" method="post">{%csrf_token%}

            <button type="submit" class="btn btn-success">Finalize checkout</button>
        </form>
{%endif%}
{%endblock%}

carts/templates/checkout_done.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block content%}
{{object.order_id}}--{{  order_obj.cart}}
<div class="col-6 mx-auto py-5 text-center">
<h1 class="display-1"> Thank you for your order!!!</h1>
    <h2>This is Order ID</h2>
</div>
{%endblock%}

carts/templates/index.html
{%extends 'base.html'%}
{%block content%}
<h1>Carts</h1>
{%if cart.cartitem_set.exists%}
<table class="table cart-table" colspan="2">
  <thead>
    <tr>
        <th scope="col">#</th>
      <th scope="col">Product Name</th>
        <th scope="col">Product Quantity</th>
         <th scope="col">Product Price</th>
         <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody class="cart-body">
    <tbody class="cart-body">
  {%for prod in cart.cartitem_set.all%}
    <tr class='cart-product'>
          <td scope="row">{{forloop.counter}}</td>
        <td><h4><a href="{{product.get_absolute_url}}">{{prod.products}}</a></h4>
        </td>
          <td>{{prod.quantity}}</td>
       <td>{{prod.products.price}}</td>
            <td ><a href="{%url 'carts:update' prod.products.slug%}?qty=0">remove</a></td>
    </tr>
  {%endfor%}

    <tr>
      <td colspan="3"></td>

      <td><b>Subtotal</b> <span class="cart-subtotal"> ${{cart.subtotal}}</span></td>

    </tr>
      <tr>
      <td colspan="3"></td>

      <td><b>total</b> <span class="cart-total"> ${{cart.total}}</span></td>

    </tr>
    <tr>
      <td colspan="3"></td>
    <td><a class="btn  btn-success" href="{%url 'carts:checkout'%}">Checkout</a></td>


    </tr>

  </tbody>
</table>


{% else %}
<p class="lead"> Cart is empty</p>
{%endif%}
{%endblock%}